### ISSUE TITLE
Payload - Generate ps1 failed and  failed to execute exe 

### ISSUE THREAD

**Issue by b4b857f6ee** [bats3c/shad0w#28]
Hello,

Your project looks like good and during testing i got few problem.

Impossible to create the beacon.ps1

![image](https://user-images.githubusercontent.com/36012515/88186147-1d972880-cc35-11ea-9a47-8df781fd9fec.png)

This is what is happening for the beacon.exe on Windows 10 x64 1703 and 1909, i think the .exe crash.

Thank you for your help :)

**Comment by b4b857f6ee** [comment]
The beacon.exe crash 

![image](https://user-images.githubusercontent.com/36012515/88187089-5f749e80-cc36-11ea-8f5e-ea44f4fa1c4c.png)

**Comment by b4b857f6ee** [comment]
I think this is the same as : https://github.com/bats3c/shad0w/issues/20

without the secure the beacon.exe without proxy work.

**Comment by bats3c** [comment]
Powershell beacon is now fixed as of commit [9a1fc54](https://github.com/bats3c/shad0w/commit/6f666150c34cad14f827eba14771de96c7eaa1d6). I will close this issue, as there is already an issue open for this exe bug
