### ISSUE TITLE
Beacon Memory Leaks

### ISSUE THREAD

**Issue by bblenard** [bats3c/shad0w#33]
The following screenshots show performance monitor graphs of a system with a beacon idling. The steady and linear increase in memory suggests the presence of a memory leak within the beacon code. The following screenshots were generated following [Microsoft's Memleak discovery guide](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/determining-whether-a-leak-exists). I look into the code and I think this is simply a lost malloc pointer.

Allocation: https://github.com/bats3c/shad0w/blob/ba0f9f0b1ea12d2033a80ef480c7ce2c92f0e4a6/beacon/src/core.c#L333-L338
Pointer Loss: https://github.com/bats3c/shad0w/blob/ba0f9f0b1ea12d2033a80ef480c7ce2c92f0e4a6/beacon/src/core.c#L402-L407

I will have to look over the code more but I think this is the source of the idle memory leak however there exists this code pattern which is also probably a source of memory leaks:
```
char*  b64_out   = (char*)malloc(out_len);

b64_out = base64_decode((const char*)Base64Buffer, out_len - 1, &out_len);
```
https://github.com/bats3c/shad0w/blob/ba0f9f0b1ea12d2033a80ef480c7ce2c92f0e4a6/beacon/src/core.c#L508-L510
https://github.com/bats3c/shad0w/blob/ba0f9f0b1ea12d2033a80ef480c7ce2c92f0e4a6/beacon/src/core.c#L532-L534

**Ten Minute Duration Test**
![performance_monitor](https://user-images.githubusercontent.com/15173997/92544295-2a86d000-f213-11ea-9f54-9f1b459e2011.png)

**Process Explorer Performance Start of Test**
![start_leak](https://user-images.githubusercontent.com/15173997/92544302-2e1a5700-f213-11ea-9958-acff95fb001d.png)

**Process Explorer Performance Middle of Test**
![middle_memleak](https://user-images.githubusercontent.com/15173997/92544308-32467480-f213-11ea-9200-dcea290a2fc8.png)

**Process Explorer Performance End of Test**
![end_leak](https://user-images.githubusercontent.com/15173997/92544311-34103800-f213-11ea-8ab0-ef30a9fa99be.png)

**Comment by bblenard** [comment]
Started working on this issue.

**Comment by bats3c** [comment]
Okay nice find, lemme know if u need a hand with the patch.

**Comment by bblenard** [comment]
I think I have _most_ of the leaks fixed in the beacon idle code path however there seems a memory leak of sorts that occurs because a new session handle is created for each iteration of `BeaconCallbackC2`. I'm not 100% sure that repeatedly calling `rWinHttpOpen` on every Callback iteration is causing the leak but that is the last bit of code that I think could and there is also [this stackoverflow post](https://stackoverflow.com/questions/12652868/winhttpopen-leaking-memory)

**~5MB memory increase over 15+ minutes of idling**
![almost_fixed](https://user-images.githubusercontent.com/15173997/92673758-815adb00-f2e1-11ea-98ae-7f9093d30445.png)
![almost_fixed_perfmon](https://user-images.githubusercontent.com/15173997/92673760-83bd3500-f2e1-11ea-837f-f6c97c1803ae.png)

Will work on cleaning up my fixes and PR them soonish :tm:

**Comment by bblenard** [comment]
PR opened for stageless beacon idle code path: https://github.com/bats3c/shad0w/pull/34

**Comment by bats3c** [comment]
This fix has been merged to [master](https://github.com/bats3c/shad0w/pull/34)
