### ISSUE TITLE
Deduplicate beacon code

### ISSUE THREAD

**Issue by bblenard** [bats3c/shad0w#42]
There is a decent amount of duplicated code within the beacons source folders. This makes implementing new features as well as bug fixes much harder because the changes have to be duplicated across multiple files. In order to improve development this code should be refactored and shared between beacon types.

**Comment by bblenard** [comment]
I'll take a look at this and try to refactor the code a bit.

**Comment by bats3c** [comment]
Yep this is an issue, that would be good thanks

**Comment by bblenard** [comment]
I got fairly far through this however it is too much work for one issue / PR. I think it would be safer to do it gradually so nothing is missed.

**Comment by bats3c** [comment]
Great to hear, yes I think that's the best way to handle it.

**Comment by bblenard** [comment]
Made some progress on this however Im running into issues with how the builds are managed. It looks like to my typically the source files are copied to either `./build` or `/tmp` and then the files are compiled. This causes issues if I try to move the shared code into a directory that isn't copied to the same relative spot. Is there a reason the source files are copied to other locations before they are compiled? why can't they be compiled in place and the result stored somewhere?

**Comment by bats3c** [comment]
Because at compile time some of the source code is changed and modified. I want to keep a fresh version with no changes which a copy can be made from and then be modified, compiled and deleted. Meaning that the original version does not change after each time a beacon is compiled.

**Comment by bblenard** [comment]
Hmmm okay I'll take a look at those. I've only seen `settings.h` and `strings.h` are there anymore you can think of?

**Comment by bats3c** [comment]
Those are the main ones, can't think of any others. Will let you know if I come across any.

**Comment by bats3c** [comment]
Closing due to being inactive
