### ISSUE TITLE
No active beacon 

### ISSUE THREAD

**Issue by merlin123h** [bats3c/shad0w#56]
Hi.
I executed shad0w for first time with port number 430 .
I got this error.
Please guide me how to solve the problem.
![yyyyy](https://user-images.githubusercontent.com/67941449/95681725-63112500-0b96-11eb-9da1-04edf57d6a80.PNG)

**Comment by bblenard** [comment]
Your screenshot doesn't really include an error. The `No Active Beacon` just means you haven't selected a beacon to interact with. From your screenshot it seems you just started the server and haven't had any beacons checkin yet. Notice how I get the same `No Active Beacon` Message when I initially start my server however once I execute a beacon on my test machine I get the initial checkin message and am able to interact and task the beacon.

# Initial Server startup
![no_beacons](https://user-images.githubusercontent.com/15173997/95689997-5b736f80-0bda-11eb-8c7d-45905190e868.png)

# Beacon Checkin
![1_beacon](https://user-images.githubusercontent.com/15173997/95690006-675f3180-0bda-11eb-8458-d007d2546f2f.png)


Also if you want to listen on port 430 you will have to publish the port via docker and instruct shad0w to listen on that port with `-p 430` at the moment you are publishing port 430 however you are still listening on the containers 443. You could also probably `--publish 430:443` to make it easy. Does that answer your questions?

**Comment by bats3c** [comment]
Nice, @bblenard covered everything you need to fix this issue.
