### ISSUE TITLE
Date and Time of Execution using Receive Task Logging

### ISSUE THREAD

**Issue by felixguerrero12** [bats3c/shad0w#58]
Submitting this to track when time of execution occurred. It is good for operators attribution when things occurred. 

Adding this to lib/path_handler.py
# Timestamping:
now = datetime.now()
date_time = now.strftime("%m/%d/%Y, %H:%M:%S")

self.shad0w.debug.log(f"Beacon ({beacon_id}) received task at {date_time}", log=True)

**Comment by bats3c** [comment]
This is a good idea. I've rewritten all the logging code on the [teamserver](https://github.com/bats3c/shad0w/tree/teamserver) branch which will soon be merged into master. If you could update this code to work with that, I'll merge it. Thanks for your work tho man

**Comment by bats3c** [comment]
Will be implemented by the teamserver
