### ISSUE TITLE
"shad0w clean" command to delete old docker containers

### ISSUE THREAD

**Issue by HeckerBirb** [bats3c/shad0w#61]
A command to clean up all old, exited docker containers would be useful because shad0w creates a new one for each command. Something along the lines of a "shad0w cleanup" command which would run `docker rm $(docker ps -a -q -f "ancestor=shad0w")` would do wonders.

**Comment by bats3c** [comment]
Nice idea, ill accept a PR :wink:

**Comment by HeckerBirb** [comment]
> 
> 
> Nice idea, ill accept a PR 😉

I'll get to it then :)

**Comment by HeckerBirb** [comment]
I realised when developing this that the proper way is not to introduce a new command - it felt awkward as well - but to (of course) add the --rm flag to the existing docker commands in `/usr/bin/shad0w`. This will automatically remove the container when it exits.
