### ISSUE TITLE
Computer name corrupt

### ISSUE THREAD

**Issue by leebaird** [bats3c/shad0w#67]
Fresh clone and build. Using a PowerShell beacon.

shad0w ≫ [i] Beacon: lee@��{        r (ARCH: x64, OS: Windows 10, Type: SECURE)
shad0w ≫
shad0w ≫ beacons
[i] 1 active beacon

+--------+---------+----------------------------+
| Number | Session |        Last Checkin        |
+--------+---------+----------------------------+
|   1    |     lee@��{      r     | 2021-01-05 16:10:04.137746 |
+--------+---------+----------------------------+

**Comment by bats3c** [comment]
Seems like an issue is implant side. I will look into this.

**Comment by glides** [comment]
Seems to be an issue with the static beacon, the staged beacon doesn't have this issue in my environment.

**Comment by bats3c** [comment]
interesting, how did you launch the above beacon?

**Comment by glides** [comment]
Beacon 1: `shad0w beacon -p x64/windows/secure -H 10.0.0.188 -f exe -o beacon.exe`
Beacon 2: `shad0w beacon -p x64/windows/secure/static -H 10.0.0.188 -f exe -o beacon-static.exe`

I just copied them to a lab server's desktop and clicked on them to launch. I ran both back to back just to capture the difference in the screenshot.

I'll take a look later tonight and submit a PR if I find it before you =D

**Comment by bats3c** [comment]
Okay cheers, wasn't sure if it was just powershell beacon. clearly not though.

Yeh would be great if u could throw up a PR. I need to rewrite the username function to use the current token at some point.

**Comment by bats3c** [comment]
Ok, the latest [commit](https://github.com/bats3c/shad0w/commit/da2286a1aa651f512af56f4cf09ab462acc6b18a) should have fixed this. Plz lemme know if anyone is still having this issue?
