### ISSUE TITLE
Most GhostPack modules are broken

### ISSUE THREAD

**Issue by leebaird** [bats3c/shad0w#68]
Working:
- rubeus
- seatbelt

Broken:
- safetykatz
- sharpchrome
- sharpdpapi
- sharpdump
- sharpup
- sharpwmi

When trying to call most of the GhostPack modules, shad0w looks in /root/shad0w/.
Suggest changing the hardcoded path to a relative path.
That way if shad0w is installed a different directory like /opt/, all of the modules should work.

**Comment by bats3c** [comment]
shad0w looks in `/root/shad0w/` because it is inside a docker container so unless the container was been built an incorrect way, this path should always be correct
