### ISSUE TITLE
Python Base64 Issue on command execution

### ISSUE THREAD

**Issue by sdhornet** [bats3c/shad0w#97]
I am able to generate, execute, and receive callbacks on beacons.

However, when I try to run commands on the beacon I am receiving the below python errors in base64.py. 

![shad0w](https://user-images.githubusercontent.com/76028034/126350778-14e846c0-5d16-4b10-94d8-de1ff487235f.png)

I followed the installation instructions from [https://blog.dylan.codes/shad0w/](https://blog.dylan.codes/shad0w/) .

**Comment by magificul** [comment]
The master branch is currently not working. You should use the latest release version as that is working. I've dm'ed batsec about this and he is working on fixing the master branch

**Comment by sdhornet** [comment]
Thanks for the update, I can't seem to get python3.8 running with the beta release, and 3.9 seems to be what is causing issues with the b64 encoding. I will just wait until the main branch is fixed.
